// <auto-generated />
namespace MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170721123300_CreateGameTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170721123300_CreateGameTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211055179__20170721123300_CreateGameTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
